### ISSUE TITLE
Create function to add recipe

### ISSUE THREAD

**Issue by kpomer** [jburger424/RecipeApp#10]
In order to customize recipes to my taste
As a user
I want to have the option to create and edit recipes

**Comment by javy47** [comment]
Creating a recipe would consist of a list of ingredients, descriptions,  and difficulty

**Comment by javy47** [comment]
It should also include the recipe's name

**Comment by imharrymargalotti** [comment]
worked for 1 hours to establish an understanding of connecting to the database. Could not test without database
