### ISSUE TITLE
Be able to search recipes based on filters. Search by different properties. Sort by number of contained inngredients

### ISSUE THREAD

**Issue by ihill116** [jburger424/RecipeApp#13]

**Comment by keselh54** [comment]
Filters include, ingredients, and/or dietary restrictions.

**Comment by keselh54** [comment]
There should be different kinds of searches. One that filters by the dietary restrictions and ingredients. One that sorts by name of the recipe. One that shows all the favorite recipes. One that shows the wishList recipes. One that shows all the recipes. And a fun one that shows a randomly chosen recipe.

**Comment by kpomer** [comment]
Done when search option allows for prioritizing/removing recipes from returned list of recipes

**Comment by keselh54** [comment]
Filters: Dietary Restrictions; Ingredients.

When the user selects filter from the command line, the UI should prompt the user for Dietary Restrictions. Then it should prompt the user for ingredients. 

After this it should then list the recipes that fit these user inputs.
