### ISSUE TITLE
User friendly UI/Edit Menus

### ISSUE THREAD

**Issue by csteel1** [jburger424/RecipeApp#51]

**Comment by keselh54** [comment]
When the UI is started it should have a list of options to choose from, and also ask the user which option they would like to choose. 

When ever the UI needs a user input, it should be clear what the user needs to enter. There should be no learning curve to the UI.

**Comment by keselh54** [comment]
Done when the UI can be operated by someone who hasn't seen the code before.

**Comment by ihill116** [comment]
3 hours for fixing up most of the new interface. Would still like to make tweaks though.

**Comment by ihill116** [comment]
Another 1.5 hours to add more commands
